package com.mardous.booming.coil.model

class AutoGeneratedImage(val type: Int, val id: Long, val songCount: Int) {

    override fun toString(): String {
        return buildString {
            append("AutoGeneratedImage{")
            append("type=$type,")
            append("id=$id,")
            append("songCount=$songCount")
            append("}")
        }
    }

    companion object {
        const val TYPE_GENRE = 1
        const val TYPE_YEAR = 2
    }
}